# Generated by Django 4.1.7 on 2023-03-01 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Strat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=512)),
                ('map', models.CharField(choices=[('de_vertigo', 'de_vertigo'), ('de_nuke', 'de_nuke'), ('de_overpass', 'de_overpass'), ('de_ancient', 'de_ancient'), ('de_inferno', 'de_inferno'), ('de_anubis', 'de_anubis'), ('de_mirage', 'de_mirage')], max_length=256)),
                ('players_required', models.IntegerField()),
                ('smokes_required', models.IntegerField()),
                ('molotovs_required', models.IntegerField()),
                ('flashbangs_required', models.IntegerField()),
                ('grenades_required', models.IntegerField()),
                ('attempts', models.IntegerField()),
                ('successes', models.IntegerField()),
                ('failures', models.IntegerField()),
                ('abandons', models.IntegerField()),
                ('description', models.CharField(max_length=2048)),
                ('cover_image', models.ImageField(upload_to='strat_images/')),
                ('video', models.FileField(upload_to='strat_videos/')),
            ],
            options={
                'verbose_name_plural': 'Strats',
            },
        ),
    ]
