# Generated by Django 4.1.7 on 2023-03-01 23:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rat_strats', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='strat',
            name='abandons',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='strat',
            name='attempts',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='strat',
            name='failures',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='strat',
            name='flashbangs_required',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='strat',
            name='grenades_required',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='strat',
            name='molotovs_required',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='strat',
            name='players_required',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='strat',
            name='smokes_required',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='strat',
            name='successes',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='strat',
            name='video',
            field=models.FileField(upload_to='strat_videos/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['MOV', 'avi', 'mp4', 'webm', 'mkv'])]),
        ),
    ]
