# Generated by Django 4.1.7 on 2023-03-01 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rat_strats', '0003_alter_strat_cover_image_alter_strat_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='strat',
            name='description',
            field=models.CharField(blank=True, max_length=2048, null=True),
        ),
    ]
