# Generated by Django 4.1.7 on 2023-03-09 01:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rat_strats', '0007_alter_strat_cover_image_alter_strat_video'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='strat',
            name='cover_image',
        ),
        migrations.RemoveField(
            model_name='strat',
            name='video',
        ),
    ]
