# Generated by Django 4.1.7 on 2023-03-09 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rat_strats', '0008_remove_strat_cover_image_remove_strat_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='strat',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='strat',
            name='video',
            field=models.CharField(blank=True, max_length=2048, null=True),
        ),
    ]
